function result = makeDSInfo()

%{
result = struct('score_each_item_only_once', NaN,...
        'absolute_windows', false, 'windows', NaN, 'absolute_reporting', ...
        false, 'reporting', NaN, 'absolute_last', false, 'last', NaN,...
        'repFactor', NaN,'strategy', NaN);
%}

result = struct('absolute_whatYouCanSee', false, 'whatYouCanSee', NaN, ...
    'absolute_budgetPerStep', false, 'budgetPerStep', NaN, 'absolute_budgetReportingFrequency',...
    false, 'budgetReportingFrequency', NaN, 'absolute_totalBudget', false,...
    'totalBudget', NaN, 'repFactor', NaN, 'strategy', NaN);
    
    
    
end

