compile:
	javac -d . -cp ".:external_jars/*" TurkHIT.java

run:
	java -cp "external_jars/*:." turkhit.TurkHIT "Sentiment Analysis" "Determine if each tweet is positive or negative" 1 0.01 0.5 tweets50.details 1,4
